PROGRAM
    : STATEMENT END{YYACCEPT;}
    ;

STATEMENT 
    :LINE
    | IF_STMT
    | STATEMENT STATEMENT
    ;

LINE 
    :ATTRIBUTION
    | PRINT_EXP
    | READ_EXP
    | DECLARATION
    | EOL
    ;
    
CONDITION
    : IDENTIFIER CONDOPERATOR NUMBER
    | IDENTIFIER CONDOPERATOR IDENTIFIER
    | NUMBER CONDOPERATOR NUMBER
    | NUMBER CONDOPERATOR IDENTIFIER
    ;

CONDOPERATOR
    : GREATER_THEN_EQUAL 
    | LESS_THEN_EQUAL 
    | NOTEQUAL 
    | LESS_THEN 
    | GREATER_THEN 
    | EQUALS_DOUBLE
    ;

BLOCK
    : O_BLOCK STATEMENT
    ;

IF_STMT
    : IF P_LEFT CONDITION P_RIGHT BLOCK C_BLOCK
    | IF P_LEFT CONDITION P_RIGHT BLOCK ELSE BLOCK C_BLOCK
    ;

ATTRIBUTION
    : IDENTIFIER EQUALS CALC EOL
    | IDENTIFIER EQUALS IDENTIFIER_CALC EOL
    ;

IDENTIFIER_CALC
    : IDENTIFIER PLUS IDENTIFIER
    | IDENTIFIER MINUS IDENTIFIER
    | IDENTIFIER DIVIDE IDENTIFIER
    | IDENTIFIER TIMES IDENTIFIER
    ;

CALC
    : NUMBER
    | CALC '+' CALC
    | CALC '-' CALC
    | CALC '/' CALC
    | CALC '*' CALC
    | '(' CALC ')'
    ;

FUNCTION
    : IDENTIFIER '(' IDENTIFIER ')' EOL
    ;

DECLARATION
    : TYPE IDENTIFIER EOL
    ;

TYPE
    : int
    | float
    ;

IDENTIFIER
    : [a-zA-Z_][_a-zA-Z0-9]*
    ;

NUMBER
    : [0-9]+(\.[0-9]+)?
    |[0-9]+
    ;
